CREATE TABLE "PERFIL" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "DESCRICAO" VARCHAR(60)
);

CREATE TABLE "USUARIO" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ID_PERFIL" INT
    "NOME" VARCHAR(50),
    "EMAIL" VARCHAR(60),
    "LOGIN" VARCHAR(30) not null,
    "SENHA" VARCHAR(20) not null
);

CREATE TABLE "SERVICO" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "DESCRICAO" VARCHAR(60)
);

CREATE TABLE "FALHA" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "DESCRICAO" VARCHAR(60)
);

CREATE TABLE "FLAVOR" (
    "ID" INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    "DESCRICAO" VARCHAR(60),
    "ID_OPEN" INTEGER
);

CREATE TABLE "IMAGEM" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "DESCRICAO" VARCHAR(60),
    "ID_OPEN" INTEGER
);

CREATE TABLE "USUARIOINSTANCIA" (
    "ID" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ID_FLAVOR" INTEGER not null,
    "ID_SERVICO" INTEGER not null,
    "ID_USUARIO" INTEGER not null,
    "ID_FALHA" INTEGER not null,
    "ID_IMAGEM" INTEGER not null,
    "NOME" VARCHAR(60)
);

CREATE TABLE "INSTANCIA" (
    "ID" PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ID_USUARIOINSTANCIA" INTEGER not null,
    "NOME" VARCHAR(60) not null,
    "STATUS" VARCHAR(60) not null,
    "IP" VARCHAR(60)
);

INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.nano');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.micro');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.tiny');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.heat');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.small');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.medium');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.large');
INSERT INTO FLAVOR (DESCRICAO) VALUES ('m1.xlarge');

INSERT INTO IMAGEM (DESCRICAO) VALUES ('FEDORA');
INSERT INTO IMAGEM (DESCRICAO) VALUES ('CIRRUS');

INSERT INTO FALHA (DESCRICAO) VALUES ('Crash');
INSERT INTO FALHA (DESCRICAO) VALUES ('Bizantina');

INSERT INTO SERVICO (DESCRICAO) VALUES ('Bronze');
INSERT INTO SERVICO (DESCRICAO) VALUES ('Prata');
INSERT INTO SERVICO (DESCRICAO) VALUES ('Ouro');