/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cloudGI.view;

import org.cloudGI.tasks.Exec;
import javax.swing.JOptionPane;
import org.cloudGI.dao.impl.DAO_BD;

/**
 *
 * @author Poliana Nascimento
 */
public class StartInstance extends javax.swing.JFrame {

    /**
     * Creates new form DeleteInstancia
     */
    public StartInstance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        close2 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Selecione o Flavor:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 160, 180, 14);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 280, 140, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 120, 227, 20);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 280, 140, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 10, 150, 60);

        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/view/images/transparencia2.png"))); // NOI18N
        getContentPane().add(close2);
        close2.setBounds(430, 5, 20, 20);

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/view/images/transparencia2.png"))); // NOI18N
        getContentPane().add(close1);
        close1.setBounds(450, 5, 20, 20);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Iniciar Instância");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 300, 40);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/view/images/Close Square.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(450, 5, 16, 16);

        close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/view/images/Minimize Square.png"))); // NOI18N
        close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close3MouseExited(evt);
            }
        });
        getContentPane().add(close3);
        close3.setBounds(430, 5, 16, 16);

        jLabel5.setText("Selecione a imagem:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 200, 97, 14);

        jLabel6.setText("Digite o nome da instancia: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 120, 132, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "m1.nano", "m1.micro" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 160, 230, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Cirrus_x86", "Fedora_x86", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 200, 230, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cloudGI/images/fundo.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 472, 320);

        setSize(new java.awt.Dimension(473, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        this.close1.setVisible(true);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        this.close1.setVisible(false);
    }//GEN-LAST:event_closeMouseExited

    private void close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseClicked
        setExtendedState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_close3MouseClicked

    private void close3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseEntered
        this.close2.setVisible(true);
    }//GEN-LAST:event_close3MouseEntered

    private void close3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close3MouseExited
        this.close2.setVisible(false);
    }//GEN-LAST:event_close3MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            DAO_BD bd = new DAO_BD();
            int flavor = bd.selectFlavor(jComboBox1.getSelectedIndex());
            String image = bd.selectImage(jComboBox2.getSelectedIndex());
            Exec ex = new Exec();            
            String command = "nova boot --flavor " + flavor + " --image " + image + " --security-groups default --key-name KeyPair01 " + jTextField1.getText();
            ex.command("source devstack/openrc admin admin; "+command);            

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JLabel close3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
